name: localization
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # todo 1: add the following packages
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # todo 2: add assets/locales/ where the language json are
  assets:
    - assets/locales/
